an_number: AN00157
project: '{{an_number}}'
title: '{{an_number}}: How to use the I2C slave library'
version: 1.0.3

documentation:
  substitutions_path: doc/substitutions.inc
  exclude_patterns_path: doc/exclude_patterns.inc
  root_doc: doc/rst/AN00157.rst
  cognidox_part_number: XM-007838-AN
  pdfs:
    doc/rst/AN00157.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{an_number}}_v{{version}}'
      pdf_short: yes
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{an_number}}_v{{version}}_readme'
      pdf_short: yes

software:
  cognidox_part_number: XM-010180-SM
